version: '3'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - 3001:80
    links:
      - mongodb
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 4200:4200
      - 49153:49153
    depends_on:
      - backend
  
  mongodb:
    image: mongo:latest
    container_name: "ngdocker_mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
        - 27017:28017